bakery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from breadapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('breadapp.urls'))
]

breadapp/urls.py
from django.urls import path
from .views import *

app_name = "breadapp"

urlpatterns = [
      path('', bread_list, name='breads'),
      path('breads/', bread_list, name='breads'),
      path('form/', bread_form, name='bread_form'),
      path('breads/<int:bread_id>', bread_details, name='bread'),
      path('breads/<int:bread_id>/form', bread_edit_form, name='bread_edit_form')
]

breadapp/models/bread.py
from django.db import models
from django.urls import reverse


class Bread(models.Model):

    name = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    ingredients = models.ManyToManyField("Ingredient", through='BreadIngredient')

    class Meta:
        verbose_name = ("Bread")
        verbose_name_plural = ("Breads")

    def __str__(self):
        return f"{self.name} ({self.region})"

    def get_absolute_url(self):
        return reverse("Bread_detail", kwargs={"pk": self.pk})

breadapp/models/bread_ingredient.py
from django.db import models


class BreadIngredient(models.Model):

    bread = models.ForeignKey("Bread", on_delete=models.CASCADE)
    ingredient = models.ForeignKey("Ingredient", on_delete=models.CASCADE)
    amount = models.CharField(max_length=25)

breadapp/models/ingredient.py
from django.db import models
from django.urls import reverse


class Ingredient(models.Model):

    name = models.CharField(max_length=100)
    local_source = models.CharField(max_length=100)
    breads = models.ManyToManyField("Bread", through='BreadIngredient')

    class Meta:
        verbose_name = ("Ingredient")
        verbose_name_plural = ("Ingredients")

    def __str__(self):
        return f"{self.name} ({self.local_source})"

    def get_absolute_url(self):
        return reverse("Ingredient_detail", kwargs={"pk": self.pk})

breadapp/models/model_factory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

breadapp/views/bread_list.py
import sqlite3
from django.shortcuts import render
from ..models import Bread, model_factory
from ..connection import Connection

def bread_list(request):
    if request.method == 'GET':
        with sqlite3.connect(Connection.db_path) as conn:
            conn.row_factory = model_factory(Bread)
            db_cursor = conn.cursor()

            db_cursor.execute("""
              SELECT
                b.id,
                b.name,
                b.region
              FROM breadapp_bread b
              ORDER BY name ASC;
            """)

            all_breads = db_cursor.fetchall()
      
      
        template = 'bread_list.html'
        context = {
          "all_breads": all_breads,
        }

        return render(request, template, context)

breadapp/views/details.py
import sqlite3
from django.urls import reverse
from django.shortcuts import render, redirect
from ..models import Bread, Ingredient, model_factory
from ..connection import Connection

def get_bread(bread_id):
  
    with sqlite3.connect(Connection.db_path) as conn:
        conn.row_factory = model_factory(Bread)
        db_cursor = conn.cursor()
        
        db_cursor.execute("""
            SELECT
              b.id,
              b.name,
              b.region
            FROM breadapp_bread b
            WHERE b.id = ?;
        """, (bread_id,))
        
        return db_cursor.fetchone()

def get_bread_ingredients(bread_id):
  
    with sqlite3.connect(Connection.db_path) as conn:
        conn.row_factory = create_bread_ingredient
        db_cursor = conn.cursor()
        
        db_cursor.execute("""
          SELECT
            bi.id,
            i.name,
            bi.amount
          FROM breadapp_ingredient i
          JOIN breadapp_breadingredient bi ON bi.ingredient_id = i.id
          WHERE bi.bread_id = ?;
        """, (bread_id,))
        
        return db_cursor.fetchall()

def create_bread_ingredient(cursor, row):
    _row = sqlite3.Row(cursor, row)

    ingredient = Ingredient()
    ingredient.bread_ingredient_id = _row["id"]
    ingredient.name = _row["name"]
    ingredient.amount = _row["amount"]

    return ingredient

def bread_details(request, bread_id):
    
    if request.method == 'GET':
        bread = get_bread(bread_id)
        ingredients = get_bread_ingredients(bread_id)
        
        template = 'breads/details.html'
        context = {
          'bread': bread,
          'ingredients': ingredients
        } 
        
        return render(request, template, context)
    
    # Check if it is a POST (as is the case with delete or edit)  
    elif request.method == "POST":
        form_data = request.POST
        
        # Check if this POST is for deleting a bread_ingredient
        if (
            "actual_method" in form_data
            # The DELETE value also has the ingredient_bread_id
            # so we need to split it and get the first part
            and form_data["actual_method"].split("--")[0] == "DELETE"
        ):
            bread_ingredient_id = form_data["actual_method"].split("--")[1]
            with sqlite3.connect(Connection.db_path) as conn:
                db_cursor = conn.cursor()

                db_cursor.execute("""
                DELETE FROM breadapp_breadingredient
                WHERE id = ?
                """, (bread_ingredient_id,))
            # This args is the bread id to pass into the path
            # https://docs.djangoproject.com/en/3.0/ref/urlresolvers/#django.urls.reverse
            return redirect(reverse('breadapp:bread', args=[bread_id]))
        
        # Check if it is an Edit
        elif (
            "actual_method" in form_data
            and form_data["actual_method"] == "PUT"
        ):
        
            with sqlite3.connect(Connection.db_path) as conn:
                db_cursor = conn.cursor()
                
                db_cursor.execute("""
                UPDATE breadapp_bread
                SET region = ?
                WHERE id = ?
                """,
                (form_data['region'], bread_id))
                
            return redirect(reverse('breadapp:bread', args=[bread_id]))

breadapp/views/form.py
import sqlite3
from django.shortcuts import render
from .details import get_bread
from ..models import Bread, model_factory
from ..connection import Connection

def bread_form(request):
    if request.method == 'GET':
        template = 'breads/form.html'
        context = {
          
        }
        
        return render(request, template, context)
    
def bread_edit_form(request, bread_id):
    if request.method == 'GET':
        bread = get_bread(bread_id)
        
        template = 'breads/form.html'
        context = {
            'bread': bread
        }
        
        return render(request, template, context)

breadapp/views/list.py
import sqlite3
from django.shortcuts import render, redirect
from django.urls import reverse
from ..models import Bread, model_factory
from ..connection import Connection

def bread_list(request):
    if request.method == 'GET':
        with sqlite3.connect(Connection.db_path) as conn:
            conn.row_factory = model_factory(Bread)
            db_cursor = conn.cursor()

            db_cursor.execute("""
              SELECT
                b.id,
                b.name,
                b.region
              FROM breadapp_bread b
              ORDER BY name ASC;
            """)

            all_breads = db_cursor.fetchall()
      
      
        template = 'breads/list.html'
        context = {
          "all_breads": all_breads,
        }

        return render(request, template, context)

    elif request.method == 'POST':
        form_data = request.POST
        
        with sqlite3.connect(Connection.db_path) as conn:
            db_cursor = conn.cursor()
            
            db_cursor.execute("""
            INSERT INTO breadapp_bread
            (name, region)
            VALUES (?, ?);
            """,
            (form_data["name"], form_data["region"]))
        
        return redirect(reverse('breadapp:breads'))

breadapp/templates/bread_list.html
{% comment %} {% extends 'shared/base.html' %} {% endcomment %}

{% block content %}
  <h1>Welcome to the Bread App</h1>

  <ol class="breads">
    {% for bread in all_breads %}
      <li class="bread">
        {{ bread.name }} {{ bread.region }}
      </li>
    {% endfor %}
  </ol>

{% endblock content %}

breadapp/templates/breads/details.html
{% comment %} {% extends 'shared/base.html' %} {% endcomment %}

{% block content %}
    
    <h1>{{ bread.name }}</h1>
    <p>Region: {{ bread.region }}</p>
    <p>Ingredients Required:</p>
    <ul>
      {% for ingredient in ingredients %}
        <li>
          {{ ingredient.name }}: {{ ingredient.amount }}
          <form 
            action="{% url 'breadapp:bread' bread.id %}" 
            method="POST" 
            style="display:inline"
          >
            {% csrf_token %}
            {% comment %} 
              The value includes the bread_ingredient_id, which is extracted
              when the POST / Delete is handled in order to delete that 
              particular relationship (without deleting the ingredient itself).
            {% endcomment %}
            <input 
              type="hidden" 
              name="actual_method" 
              value="DELETE--{{ ingredient.bread_ingredient_id }}"
            >
            <button>Delete</button>
          </form>
        </li>
      {% endfor %}
    </ul>

    <form action="{% url 'breadapp:bread_edit_form' bread.id %}" method="GET">
        {% csrf_token %}
        <button>Edit Bread</button>
    </form>

{% endblock %}

breadapp/templates/breads/form.html
{% comment %} {% extends 'shared/base.html' %} {% endcomment %}

{% block content %}
  <h2>Bread Form</h2>

  {% if bread.id is not None %}
    <form action="{% url 'breadapp:bread' bread.id %}" method="post">
  {% else %}
    <form action="{% url 'breadapp:breads' %}" method="post">
  {% endif %} 

      {% csrf_token %}
      <fieldset>
          <label for="name">Name: </label>
          <input 
            id="name" 
            type="text" 
            name="name" 
            value="{{ bread.name }}"
            {% comment %} 
                The name field is Disabled if this is an edit
                per the exercise requirements
            {% endcomment %}
            {% if bread.id is not None %}
            disabled
            {% endif %}
          >
      </fieldset>

      <fieldset>
        <label for="region">Region: </label>
        <input id="region" type="text" name="region" value="{{ bread.region }}">
      </fieldset>

      {% if bread.id is not None %}
        <input type="hidden" name="actual_method" value="PUT">
        <input type="submit" value="Update" />
      {% else %}
        <input type="submit" value="Create" />
      {% endif %}

    </form>

{% endblock content %}

breadapp/templates/breads/list.html
{% comment %} {% extends 'shared/base.html' %} {% endcomment %}

{% block content %}
  <h2>Bread List</h2>

  <a href="{% url 'breadapp:bread_form' %}">
    Add New Bread
  </a>


  <ol class="breads">
    {% for bread in all_breads %}
      <li class="bread">
        <a href="{% url 'breadapp:bread' bread.id %}">
          {{ bread.name }}: {{ bread.region }}
        </a>
      </li>
    {% endfor %}
  </ol>

{% endblock content %}